name: Orbis505

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        # Checkout the repository
      - uses: actions/checkout@v2
        # Install required stuff needed to build Mira
      - name: preinstall
        run: sudo apt install build-essential git clang lldb clang-tidy clang-tools cppcheck
        # Handle loader crap
      - name: create loader directories
        run: cd loader; make create
      - name: clean loader
        run: cd loader; make clean
      - name: create mira directories
        run: make create
      - name: clean mira
        run: make clean
        # 6.72 Support
      - name: make 6.72 loader
        run: cd loader; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_672 MIRA_CHECKS=TRUE make
      - name: make 6.72 elf
        run: MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_672 MIRA_CHECKS=TRUE make
      - name: Upload 6.72 loader
        uses: actions/upload-artifact@v2
        with:
          name: MiraLoader_Orbis_MIRA_PLATFORM_ORBIS_BSD_672.bin
          path: loader/build/MiraLoader_Orbis_MIRA_PLATFORM_ORBIS_BSD_672.bin
      - name: Upload 6.72 elf
        uses: actions/upload-artifact@v2
        with:
          name: Mira_Orbis_MIRA_PLATFORM_ORBIS_BSD_672.elf
          path: build/Mira_Orbis_MIRA_PLATFORM_ORBIS_BSD_672.elf
